;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2024 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 48-2137-ACAB-99                      |
; |                            Horion-Crack-2015                            |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 15725363B1DA715BDC8478DCE9665444736DB7AA483F7E78D59DF72FAA2F4239
; Input MD5    : 7EEF8FA91F133727E46608376493B291
; Input CRC32  : 6C07E510

; ---------------------------------------------------------------------------
; File Name   : D:\!Files\src\Reversed\pseudocode\clutt3.5\asm\clutt3.5.bin
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 0200h Loaded length: 0200h

; ===========================================================================

; Segment type: Pure code
                mov     ah, 0
                mov     al, 13h
                int     10h             ; - VIDEO - SET VIDEO MODE
                                        ; AL = mode
                mov     ax, 0A000h
                mov     es, ax
                xor     di, di
                mov     cx, 0

loc_10:                                 ; CODE XREF: seg000:0017↓j seg000:001D↓j
                mov     es:[di], al
                inc     di
                cmp     di, 0FFFFh
                je      loc_10
                inc     al
                xor     di, di
                jmp     loc_10
; ---------------------------------------------------------------------------
times 510 - ($-$$) db 0
dw      0AA55h